version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: todolist
    ports:
        - 27017:27017
        - 9229:9229
    volumes:
        - ./mongo-init:/docker-entrypoint-initdb.d/:ro

  compass:
    image: haohanyang/compass-web
    container_name: compass-web-dev-compass
    environment:
      - CW_MONGO_URI=mongodb://changeme:changeme@mongo:27017/todolist?authSource=admin
      - CW_BASIC_AUTH_USERNAME=changeme
      - CW_BASIC_AUTH_PASSWORD=changeme
    depends_on:
      - mongo
    ports:
      - 8080:8080
    links:
      - mongo

  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/todolist:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      clientOptions: mongodb://changeme:changeme@mongo:27017/todolist
