version: "3.8"
services:
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/todolist-mongo-go:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: todolist
volumes:
  mongodata: {}
