version: "3.8"
services:
  todolist:
    image: quay.io/migtools/oadp-ci-todolist-mariadb-go
    restart: always
    ports:
      - 8000:8000
    volumes:
      - dbvol:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: root
volumes:
  dbvol: {}
